// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileBlockMsg.proto

#include "FileBlockMsg.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace hh {
PROTOBUF_CONSTEXPR FileBlockMsg::FileBlockMsg(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.server_type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.filename__)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.fileblockbuffer__)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.stid_)*/0u
  , /*decltype(_impl_.dtid_)*/0u
  , /*decltype(_impl_.fileblocknumber__)*/uint64_t{0u}
  , /*decltype(_impl_.fileblocknumber_total__)*/uint64_t{0u}
  , /*decltype(_impl_.fileblocksize__)*/uint64_t{0u}
  , /*decltype(_impl_.filesize_total__)*/uint64_t{0u}
  , /*decltype(_impl_.fileid__)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FileBlockMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileBlockMsgDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileBlockMsgDefaultTypeInternal() {}
  union {
    FileBlockMsg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileBlockMsgDefaultTypeInternal _FileBlockMsg_default_instance_;
PROTOBUF_CONSTEXPR RecvFinishMsg::RecvFinishMsg(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.server_type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.filename_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.strmsg_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.stid_)*/0u
  , /*decltype(_impl_.dtid_)*/0u
  , /*decltype(_impl_.intmsg_)*/uint64_t{0u}
  , /*decltype(_impl_.dblmsg_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RecvFinishMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RecvFinishMsgDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RecvFinishMsgDefaultTypeInternal() {}
  union {
    RecvFinishMsg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RecvFinishMsgDefaultTypeInternal _RecvFinishMsg_default_instance_;
}  // namespace hh
static ::_pb::Metadata file_level_metadata_FileBlockMsg_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_FileBlockMsg_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_FileBlockMsg_2eproto = nullptr;

const uint32_t TableStruct_FileBlockMsg_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hh::FileBlockMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hh::FileBlockMsg, _impl_.server_type_),
  PROTOBUF_FIELD_OFFSET(::hh::FileBlockMsg, _impl_.stid_),
  PROTOBUF_FIELD_OFFSET(::hh::FileBlockMsg, _impl_.dtid_),
  PROTOBUF_FIELD_OFFSET(::hh::FileBlockMsg, _impl_.fileid__),
  PROTOBUF_FIELD_OFFSET(::hh::FileBlockMsg, _impl_.fileblocknumber__),
  PROTOBUF_FIELD_OFFSET(::hh::FileBlockMsg, _impl_.fileblocknumber_total__),
  PROTOBUF_FIELD_OFFSET(::hh::FileBlockMsg, _impl_.fileblocksize__),
  PROTOBUF_FIELD_OFFSET(::hh::FileBlockMsg, _impl_.filesize_total__),
  PROTOBUF_FIELD_OFFSET(::hh::FileBlockMsg, _impl_.filename__),
  PROTOBUF_FIELD_OFFSET(::hh::FileBlockMsg, _impl_.fileblockbuffer__),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hh::RecvFinishMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hh::RecvFinishMsg, _impl_.server_type_),
  PROTOBUF_FIELD_OFFSET(::hh::RecvFinishMsg, _impl_.stid_),
  PROTOBUF_FIELD_OFFSET(::hh::RecvFinishMsg, _impl_.dtid_),
  PROTOBUF_FIELD_OFFSET(::hh::RecvFinishMsg, _impl_.filename_),
  PROTOBUF_FIELD_OFFSET(::hh::RecvFinishMsg, _impl_.strmsg_),
  PROTOBUF_FIELD_OFFSET(::hh::RecvFinishMsg, _impl_.intmsg_),
  PROTOBUF_FIELD_OFFSET(::hh::RecvFinishMsg, _impl_.dblmsg_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::hh::FileBlockMsg)},
  { 16, -1, -1, sizeof(::hh::RecvFinishMsg)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::hh::_FileBlockMsg_default_instance_._instance,
  &::hh::_RecvFinishMsg_default_instance_._instance,
};

const char descriptor_table_protodef_FileBlockMsg_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022FileBlockMsg.proto\022\002hh\"\350\001\n\014FileBlockMs"
  "g\022\023\n\013server_type\030\001 \001(\t\022\014\n\004sTID\030\002 \001(\r\022\014\n\004"
  "dTID\030\003 \001(\r\022\017\n\007FileID_\030\004 \001(\r\022\030\n\020FileBlock"
  "Number_\030\005 \001(\004\022\036\n\026FileBlockNumber_total_\030"
  "\006 \001(\004\022\026\n\016FileBlockSize_\030\007 \001(\004\022\027\n\017FileSiz"
  "e_total_\030\010 \001(\004\022\021\n\tFileName_\030\t \001(\t\022\030\n\020Fil"
  "eBlockBuffer_\030\n \001(\014\"\202\001\n\rRecvFinishMsg\022\023\n"
  "\013server_type\030\001 \001(\t\022\014\n\004sTID\030\002 \001(\r\022\014\n\004dTID"
  "\030\003 \001(\r\022\020\n\010FileName\030\004 \001(\t\022\016\n\006StrMsg\030\005 \001(\t"
  "\022\016\n\006intMsg\030\006 \001(\004\022\016\n\006dblMsg\030\007 \001(\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_FileBlockMsg_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_FileBlockMsg_2eproto = {
    false, false, 400, descriptor_table_protodef_FileBlockMsg_2eproto,
    "FileBlockMsg.proto",
    &descriptor_table_FileBlockMsg_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_FileBlockMsg_2eproto::offsets,
    file_level_metadata_FileBlockMsg_2eproto, file_level_enum_descriptors_FileBlockMsg_2eproto,
    file_level_service_descriptors_FileBlockMsg_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_FileBlockMsg_2eproto_getter() {
  return &descriptor_table_FileBlockMsg_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_FileBlockMsg_2eproto(&descriptor_table_FileBlockMsg_2eproto);
namespace hh {

// ===================================================================

class FileBlockMsg::_Internal {
 public:
};

FileBlockMsg::FileBlockMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hh.FileBlockMsg)
}
FileBlockMsg::FileBlockMsg(const FileBlockMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FileBlockMsg* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.server_type_){}
    , decltype(_impl_.filename__){}
    , decltype(_impl_.fileblockbuffer__){}
    , decltype(_impl_.stid_){}
    , decltype(_impl_.dtid_){}
    , decltype(_impl_.fileblocknumber__){}
    , decltype(_impl_.fileblocknumber_total__){}
    , decltype(_impl_.fileblocksize__){}
    , decltype(_impl_.filesize_total__){}
    , decltype(_impl_.fileid__){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.server_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.server_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_server_type().empty()) {
    _this->_impl_.server_type_.Set(from._internal_server_type(), 
      _this->GetArenaForAllocation());
  }
  _impl_.filename__.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filename__.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_filename_().empty()) {
    _this->_impl_.filename__.Set(from._internal_filename_(), 
      _this->GetArenaForAllocation());
  }
  _impl_.fileblockbuffer__.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.fileblockbuffer__.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_fileblockbuffer_().empty()) {
    _this->_impl_.fileblockbuffer__.Set(from._internal_fileblockbuffer_(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.stid_, &from._impl_.stid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.fileid__) -
    reinterpret_cast<char*>(&_impl_.stid_)) + sizeof(_impl_.fileid__));
  // @@protoc_insertion_point(copy_constructor:hh.FileBlockMsg)
}

inline void FileBlockMsg::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.server_type_){}
    , decltype(_impl_.filename__){}
    , decltype(_impl_.fileblockbuffer__){}
    , decltype(_impl_.stid_){0u}
    , decltype(_impl_.dtid_){0u}
    , decltype(_impl_.fileblocknumber__){uint64_t{0u}}
    , decltype(_impl_.fileblocknumber_total__){uint64_t{0u}}
    , decltype(_impl_.fileblocksize__){uint64_t{0u}}
    , decltype(_impl_.filesize_total__){uint64_t{0u}}
    , decltype(_impl_.fileid__){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.server_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.server_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.filename__.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filename__.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.fileblockbuffer__.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.fileblockbuffer__.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

FileBlockMsg::~FileBlockMsg() {
  // @@protoc_insertion_point(destructor:hh.FileBlockMsg)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FileBlockMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.server_type_.Destroy();
  _impl_.filename__.Destroy();
  _impl_.fileblockbuffer__.Destroy();
}

void FileBlockMsg::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FileBlockMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:hh.FileBlockMsg)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.server_type_.ClearToEmpty();
  _impl_.filename__.ClearToEmpty();
  _impl_.fileblockbuffer__.ClearToEmpty();
  ::memset(&_impl_.stid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.fileid__) -
      reinterpret_cast<char*>(&_impl_.stid_)) + sizeof(_impl_.fileid__));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FileBlockMsg::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string server_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_server_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "hh.FileBlockMsg.server_type"));
        } else
          goto handle_unusual;
        continue;
      // uint32 sTID = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.stid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 dTID = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.dtid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 FileID_ = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.fileid__ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 FileBlockNumber_ = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.fileblocknumber__ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 FileBlockNumber_total_ = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.fileblocknumber_total__ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 FileBlockSize_ = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.fileblocksize__ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 FileSize_total_ = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.filesize_total__ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string FileName_ = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          auto str = _internal_mutable_filename_();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "hh.FileBlockMsg.FileName_"));
        } else
          goto handle_unusual;
        continue;
      // bytes FileBlockBuffer_ = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          auto str = _internal_mutable_fileblockbuffer_();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FileBlockMsg::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hh.FileBlockMsg)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string server_type = 1;
  if (!this->_internal_server_type().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_server_type().data(), static_cast<int>(this->_internal_server_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "hh.FileBlockMsg.server_type");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_server_type(), target);
  }

  // uint32 sTID = 2;
  if (this->_internal_stid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_stid(), target);
  }

  // uint32 dTID = 3;
  if (this->_internal_dtid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_dtid(), target);
  }

  // uint32 FileID_ = 4;
  if (this->_internal_fileid_() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_fileid_(), target);
  }

  // uint64 FileBlockNumber_ = 5;
  if (this->_internal_fileblocknumber_() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(5, this->_internal_fileblocknumber_(), target);
  }

  // uint64 FileBlockNumber_total_ = 6;
  if (this->_internal_fileblocknumber_total_() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(6, this->_internal_fileblocknumber_total_(), target);
  }

  // uint64 FileBlockSize_ = 7;
  if (this->_internal_fileblocksize_() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(7, this->_internal_fileblocksize_(), target);
  }

  // uint64 FileSize_total_ = 8;
  if (this->_internal_filesize_total_() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(8, this->_internal_filesize_total_(), target);
  }

  // string FileName_ = 9;
  if (!this->_internal_filename_().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_filename_().data(), static_cast<int>(this->_internal_filename_().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "hh.FileBlockMsg.FileName_");
    target = stream->WriteStringMaybeAliased(
        9, this->_internal_filename_(), target);
  }

  // bytes FileBlockBuffer_ = 10;
  if (!this->_internal_fileblockbuffer_().empty()) {
    target = stream->WriteBytesMaybeAliased(
        10, this->_internal_fileblockbuffer_(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hh.FileBlockMsg)
  return target;
}

size_t FileBlockMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hh.FileBlockMsg)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string server_type = 1;
  if (!this->_internal_server_type().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_server_type());
  }

  // string FileName_ = 9;
  if (!this->_internal_filename_().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_filename_());
  }

  // bytes FileBlockBuffer_ = 10;
  if (!this->_internal_fileblockbuffer_().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_fileblockbuffer_());
  }

  // uint32 sTID = 2;
  if (this->_internal_stid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_stid());
  }

  // uint32 dTID = 3;
  if (this->_internal_dtid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_dtid());
  }

  // uint64 FileBlockNumber_ = 5;
  if (this->_internal_fileblocknumber_() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_fileblocknumber_());
  }

  // uint64 FileBlockNumber_total_ = 6;
  if (this->_internal_fileblocknumber_total_() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_fileblocknumber_total_());
  }

  // uint64 FileBlockSize_ = 7;
  if (this->_internal_fileblocksize_() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_fileblocksize_());
  }

  // uint64 FileSize_total_ = 8;
  if (this->_internal_filesize_total_() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_filesize_total_());
  }

  // uint32 FileID_ = 4;
  if (this->_internal_fileid_() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_fileid_());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FileBlockMsg::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FileBlockMsg::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FileBlockMsg::GetClassData() const { return &_class_data_; }


void FileBlockMsg::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FileBlockMsg*>(&to_msg);
  auto& from = static_cast<const FileBlockMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hh.FileBlockMsg)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_server_type().empty()) {
    _this->_internal_set_server_type(from._internal_server_type());
  }
  if (!from._internal_filename_().empty()) {
    _this->_internal_set_filename_(from._internal_filename_());
  }
  if (!from._internal_fileblockbuffer_().empty()) {
    _this->_internal_set_fileblockbuffer_(from._internal_fileblockbuffer_());
  }
  if (from._internal_stid() != 0) {
    _this->_internal_set_stid(from._internal_stid());
  }
  if (from._internal_dtid() != 0) {
    _this->_internal_set_dtid(from._internal_dtid());
  }
  if (from._internal_fileblocknumber_() != 0) {
    _this->_internal_set_fileblocknumber_(from._internal_fileblocknumber_());
  }
  if (from._internal_fileblocknumber_total_() != 0) {
    _this->_internal_set_fileblocknumber_total_(from._internal_fileblocknumber_total_());
  }
  if (from._internal_fileblocksize_() != 0) {
    _this->_internal_set_fileblocksize_(from._internal_fileblocksize_());
  }
  if (from._internal_filesize_total_() != 0) {
    _this->_internal_set_filesize_total_(from._internal_filesize_total_());
  }
  if (from._internal_fileid_() != 0) {
    _this->_internal_set_fileid_(from._internal_fileid_());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FileBlockMsg::CopyFrom(const FileBlockMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hh.FileBlockMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FileBlockMsg::IsInitialized() const {
  return true;
}

void FileBlockMsg::InternalSwap(FileBlockMsg* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.server_type_, lhs_arena,
      &other->_impl_.server_type_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.filename__, lhs_arena,
      &other->_impl_.filename__, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.fileblockbuffer__, lhs_arena,
      &other->_impl_.fileblockbuffer__, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FileBlockMsg, _impl_.fileid__)
      + sizeof(FileBlockMsg::_impl_.fileid__)
      - PROTOBUF_FIELD_OFFSET(FileBlockMsg, _impl_.stid_)>(
          reinterpret_cast<char*>(&_impl_.stid_),
          reinterpret_cast<char*>(&other->_impl_.stid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata FileBlockMsg::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_FileBlockMsg_2eproto_getter, &descriptor_table_FileBlockMsg_2eproto_once,
      file_level_metadata_FileBlockMsg_2eproto[0]);
}

// ===================================================================

class RecvFinishMsg::_Internal {
 public:
};

RecvFinishMsg::RecvFinishMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hh.RecvFinishMsg)
}
RecvFinishMsg::RecvFinishMsg(const RecvFinishMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RecvFinishMsg* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.server_type_){}
    , decltype(_impl_.filename_){}
    , decltype(_impl_.strmsg_){}
    , decltype(_impl_.stid_){}
    , decltype(_impl_.dtid_){}
    , decltype(_impl_.intmsg_){}
    , decltype(_impl_.dblmsg_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.server_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.server_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_server_type().empty()) {
    _this->_impl_.server_type_.Set(from._internal_server_type(), 
      _this->GetArenaForAllocation());
  }
  _impl_.filename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_filename().empty()) {
    _this->_impl_.filename_.Set(from._internal_filename(), 
      _this->GetArenaForAllocation());
  }
  _impl_.strmsg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.strmsg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_strmsg().empty()) {
    _this->_impl_.strmsg_.Set(from._internal_strmsg(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.stid_, &from._impl_.stid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.dblmsg_) -
    reinterpret_cast<char*>(&_impl_.stid_)) + sizeof(_impl_.dblmsg_));
  // @@protoc_insertion_point(copy_constructor:hh.RecvFinishMsg)
}

inline void RecvFinishMsg::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.server_type_){}
    , decltype(_impl_.filename_){}
    , decltype(_impl_.strmsg_){}
    , decltype(_impl_.stid_){0u}
    , decltype(_impl_.dtid_){0u}
    , decltype(_impl_.intmsg_){uint64_t{0u}}
    , decltype(_impl_.dblmsg_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.server_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.server_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.filename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.strmsg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.strmsg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RecvFinishMsg::~RecvFinishMsg() {
  // @@protoc_insertion_point(destructor:hh.RecvFinishMsg)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RecvFinishMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.server_type_.Destroy();
  _impl_.filename_.Destroy();
  _impl_.strmsg_.Destroy();
}

void RecvFinishMsg::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RecvFinishMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:hh.RecvFinishMsg)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.server_type_.ClearToEmpty();
  _impl_.filename_.ClearToEmpty();
  _impl_.strmsg_.ClearToEmpty();
  ::memset(&_impl_.stid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.dblmsg_) -
      reinterpret_cast<char*>(&_impl_.stid_)) + sizeof(_impl_.dblmsg_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RecvFinishMsg::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string server_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_server_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "hh.RecvFinishMsg.server_type"));
        } else
          goto handle_unusual;
        continue;
      // uint32 sTID = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.stid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 dTID = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.dtid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string FileName = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_filename();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "hh.RecvFinishMsg.FileName"));
        } else
          goto handle_unusual;
        continue;
      // string StrMsg = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_strmsg();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "hh.RecvFinishMsg.StrMsg"));
        } else
          goto handle_unusual;
        continue;
      // uint64 intMsg = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.intmsg_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double dblMsg = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 57)) {
          _impl_.dblmsg_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RecvFinishMsg::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hh.RecvFinishMsg)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string server_type = 1;
  if (!this->_internal_server_type().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_server_type().data(), static_cast<int>(this->_internal_server_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "hh.RecvFinishMsg.server_type");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_server_type(), target);
  }

  // uint32 sTID = 2;
  if (this->_internal_stid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_stid(), target);
  }

  // uint32 dTID = 3;
  if (this->_internal_dtid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_dtid(), target);
  }

  // string FileName = 4;
  if (!this->_internal_filename().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_filename().data(), static_cast<int>(this->_internal_filename().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "hh.RecvFinishMsg.FileName");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_filename(), target);
  }

  // string StrMsg = 5;
  if (!this->_internal_strmsg().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_strmsg().data(), static_cast<int>(this->_internal_strmsg().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "hh.RecvFinishMsg.StrMsg");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_strmsg(), target);
  }

  // uint64 intMsg = 6;
  if (this->_internal_intmsg() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(6, this->_internal_intmsg(), target);
  }

  // double dblMsg = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_dblmsg = this->_internal_dblmsg();
  uint64_t raw_dblmsg;
  memcpy(&raw_dblmsg, &tmp_dblmsg, sizeof(tmp_dblmsg));
  if (raw_dblmsg != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(7, this->_internal_dblmsg(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hh.RecvFinishMsg)
  return target;
}

size_t RecvFinishMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hh.RecvFinishMsg)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string server_type = 1;
  if (!this->_internal_server_type().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_server_type());
  }

  // string FileName = 4;
  if (!this->_internal_filename().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_filename());
  }

  // string StrMsg = 5;
  if (!this->_internal_strmsg().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_strmsg());
  }

  // uint32 sTID = 2;
  if (this->_internal_stid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_stid());
  }

  // uint32 dTID = 3;
  if (this->_internal_dtid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_dtid());
  }

  // uint64 intMsg = 6;
  if (this->_internal_intmsg() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_intmsg());
  }

  // double dblMsg = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_dblmsg = this->_internal_dblmsg();
  uint64_t raw_dblmsg;
  memcpy(&raw_dblmsg, &tmp_dblmsg, sizeof(tmp_dblmsg));
  if (raw_dblmsg != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RecvFinishMsg::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RecvFinishMsg::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RecvFinishMsg::GetClassData() const { return &_class_data_; }


void RecvFinishMsg::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RecvFinishMsg*>(&to_msg);
  auto& from = static_cast<const RecvFinishMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hh.RecvFinishMsg)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_server_type().empty()) {
    _this->_internal_set_server_type(from._internal_server_type());
  }
  if (!from._internal_filename().empty()) {
    _this->_internal_set_filename(from._internal_filename());
  }
  if (!from._internal_strmsg().empty()) {
    _this->_internal_set_strmsg(from._internal_strmsg());
  }
  if (from._internal_stid() != 0) {
    _this->_internal_set_stid(from._internal_stid());
  }
  if (from._internal_dtid() != 0) {
    _this->_internal_set_dtid(from._internal_dtid());
  }
  if (from._internal_intmsg() != 0) {
    _this->_internal_set_intmsg(from._internal_intmsg());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_dblmsg = from._internal_dblmsg();
  uint64_t raw_dblmsg;
  memcpy(&raw_dblmsg, &tmp_dblmsg, sizeof(tmp_dblmsg));
  if (raw_dblmsg != 0) {
    _this->_internal_set_dblmsg(from._internal_dblmsg());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RecvFinishMsg::CopyFrom(const RecvFinishMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hh.RecvFinishMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RecvFinishMsg::IsInitialized() const {
  return true;
}

void RecvFinishMsg::InternalSwap(RecvFinishMsg* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.server_type_, lhs_arena,
      &other->_impl_.server_type_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.filename_, lhs_arena,
      &other->_impl_.filename_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.strmsg_, lhs_arena,
      &other->_impl_.strmsg_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RecvFinishMsg, _impl_.dblmsg_)
      + sizeof(RecvFinishMsg::_impl_.dblmsg_)
      - PROTOBUF_FIELD_OFFSET(RecvFinishMsg, _impl_.stid_)>(
          reinterpret_cast<char*>(&_impl_.stid_),
          reinterpret_cast<char*>(&other->_impl_.stid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RecvFinishMsg::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_FileBlockMsg_2eproto_getter, &descriptor_table_FileBlockMsg_2eproto_once,
      file_level_metadata_FileBlockMsg_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace hh
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::hh::FileBlockMsg*
Arena::CreateMaybeMessage< ::hh::FileBlockMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hh::FileBlockMsg >(arena);
}
template<> PROTOBUF_NOINLINE ::hh::RecvFinishMsg*
Arena::CreateMaybeMessage< ::hh::RecvFinishMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hh::RecvFinishMsg >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
