// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileBlockMsg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_FileBlockMsg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_FileBlockMsg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_FileBlockMsg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_FileBlockMsg_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_FileBlockMsg_2eproto;
namespace hh {
class FileBlockMsg;
struct FileBlockMsgDefaultTypeInternal;
extern FileBlockMsgDefaultTypeInternal _FileBlockMsg_default_instance_;
class RecvFinishMsg;
struct RecvFinishMsgDefaultTypeInternal;
extern RecvFinishMsgDefaultTypeInternal _RecvFinishMsg_default_instance_;
}  // namespace hh
PROTOBUF_NAMESPACE_OPEN
template<> ::hh::FileBlockMsg* Arena::CreateMaybeMessage<::hh::FileBlockMsg>(Arena*);
template<> ::hh::RecvFinishMsg* Arena::CreateMaybeMessage<::hh::RecvFinishMsg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace hh {

// ===================================================================

class FileBlockMsg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hh.FileBlockMsg) */ {
 public:
  inline FileBlockMsg() : FileBlockMsg(nullptr) {}
  ~FileBlockMsg() override;
  explicit PROTOBUF_CONSTEXPR FileBlockMsg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FileBlockMsg(const FileBlockMsg& from);
  FileBlockMsg(FileBlockMsg&& from) noexcept
    : FileBlockMsg() {
    *this = ::std::move(from);
  }

  inline FileBlockMsg& operator=(const FileBlockMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileBlockMsg& operator=(FileBlockMsg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileBlockMsg& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileBlockMsg* internal_default_instance() {
    return reinterpret_cast<const FileBlockMsg*>(
               &_FileBlockMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FileBlockMsg& a, FileBlockMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(FileBlockMsg* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileBlockMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileBlockMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FileBlockMsg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FileBlockMsg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FileBlockMsg& from) {
    FileBlockMsg::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileBlockMsg* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hh.FileBlockMsg";
  }
  protected:
  explicit FileBlockMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServerTypeFieldNumber = 1,
    kFileNameFieldNumber = 9,
    kFileBlockBufferFieldNumber = 10,
    kSTIDFieldNumber = 2,
    kDTIDFieldNumber = 3,
    kFileBlockNumberFieldNumber = 5,
    kFileBlockNumberTotalFieldNumber = 6,
    kFileBlockSizeFieldNumber = 7,
    kFileSizeTotalFieldNumber = 8,
    kFileIDFieldNumber = 4,
  };
  // string server_type = 1;
  void clear_server_type();
  const std::string& server_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_server_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_server_type();
  PROTOBUF_NODISCARD std::string* release_server_type();
  void set_allocated_server_type(std::string* server_type);
  private:
  const std::string& _internal_server_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_server_type(const std::string& value);
  std::string* _internal_mutable_server_type();
  public:

  // string FileName_ = 9;
  void clear_filename_();
  const std::string& filename_() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_filename_(ArgT0&& arg0, ArgT... args);
  std::string* mutable_filename_();
  PROTOBUF_NODISCARD std::string* release_filename_();
  void set_allocated_filename_(std::string* filename_);
  private:
  const std::string& _internal_filename_() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filename_(const std::string& value);
  std::string* _internal_mutable_filename_();
  public:

  // bytes FileBlockBuffer_ = 10;
  void clear_fileblockbuffer_();
  const std::string& fileblockbuffer_() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_fileblockbuffer_(ArgT0&& arg0, ArgT... args);
  std::string* mutable_fileblockbuffer_();
  PROTOBUF_NODISCARD std::string* release_fileblockbuffer_();
  void set_allocated_fileblockbuffer_(std::string* fileblockbuffer_);
  private:
  const std::string& _internal_fileblockbuffer_() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_fileblockbuffer_(const std::string& value);
  std::string* _internal_mutable_fileblockbuffer_();
  public:

  // uint32 sTID = 2;
  void clear_stid();
  uint32_t stid() const;
  void set_stid(uint32_t value);
  private:
  uint32_t _internal_stid() const;
  void _internal_set_stid(uint32_t value);
  public:

  // uint32 dTID = 3;
  void clear_dtid();
  uint32_t dtid() const;
  void set_dtid(uint32_t value);
  private:
  uint32_t _internal_dtid() const;
  void _internal_set_dtid(uint32_t value);
  public:

  // uint64 FileBlockNumber_ = 5;
  void clear_fileblocknumber_();
  uint64_t fileblocknumber_() const;
  void set_fileblocknumber_(uint64_t value);
  private:
  uint64_t _internal_fileblocknumber_() const;
  void _internal_set_fileblocknumber_(uint64_t value);
  public:

  // uint64 FileBlockNumber_total_ = 6;
  void clear_fileblocknumber_total_();
  uint64_t fileblocknumber_total_() const;
  void set_fileblocknumber_total_(uint64_t value);
  private:
  uint64_t _internal_fileblocknumber_total_() const;
  void _internal_set_fileblocknumber_total_(uint64_t value);
  public:

  // uint64 FileBlockSize_ = 7;
  void clear_fileblocksize_();
  uint64_t fileblocksize_() const;
  void set_fileblocksize_(uint64_t value);
  private:
  uint64_t _internal_fileblocksize_() const;
  void _internal_set_fileblocksize_(uint64_t value);
  public:

  // uint64 FileSize_total_ = 8;
  void clear_filesize_total_();
  uint64_t filesize_total_() const;
  void set_filesize_total_(uint64_t value);
  private:
  uint64_t _internal_filesize_total_() const;
  void _internal_set_filesize_total_(uint64_t value);
  public:

  // uint32 FileID_ = 4;
  void clear_fileid_();
  uint32_t fileid_() const;
  void set_fileid_(uint32_t value);
  private:
  uint32_t _internal_fileid_() const;
  void _internal_set_fileid_(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:hh.FileBlockMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr server_type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filename__;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fileblockbuffer__;
    uint32_t stid_;
    uint32_t dtid_;
    uint64_t fileblocknumber__;
    uint64_t fileblocknumber_total__;
    uint64_t fileblocksize__;
    uint64_t filesize_total__;
    uint32_t fileid__;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_FileBlockMsg_2eproto;
};
// -------------------------------------------------------------------

class RecvFinishMsg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hh.RecvFinishMsg) */ {
 public:
  inline RecvFinishMsg() : RecvFinishMsg(nullptr) {}
  ~RecvFinishMsg() override;
  explicit PROTOBUF_CONSTEXPR RecvFinishMsg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RecvFinishMsg(const RecvFinishMsg& from);
  RecvFinishMsg(RecvFinishMsg&& from) noexcept
    : RecvFinishMsg() {
    *this = ::std::move(from);
  }

  inline RecvFinishMsg& operator=(const RecvFinishMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline RecvFinishMsg& operator=(RecvFinishMsg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RecvFinishMsg& default_instance() {
    return *internal_default_instance();
  }
  static inline const RecvFinishMsg* internal_default_instance() {
    return reinterpret_cast<const RecvFinishMsg*>(
               &_RecvFinishMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RecvFinishMsg& a, RecvFinishMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(RecvFinishMsg* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RecvFinishMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RecvFinishMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RecvFinishMsg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RecvFinishMsg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RecvFinishMsg& from) {
    RecvFinishMsg::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RecvFinishMsg* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hh.RecvFinishMsg";
  }
  protected:
  explicit RecvFinishMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServerTypeFieldNumber = 1,
    kFileNameFieldNumber = 4,
    kStrMsgFieldNumber = 5,
    kSTIDFieldNumber = 2,
    kDTIDFieldNumber = 3,
    kIntMsgFieldNumber = 6,
    kDblMsgFieldNumber = 7,
  };
  // string server_type = 1;
  void clear_server_type();
  const std::string& server_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_server_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_server_type();
  PROTOBUF_NODISCARD std::string* release_server_type();
  void set_allocated_server_type(std::string* server_type);
  private:
  const std::string& _internal_server_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_server_type(const std::string& value);
  std::string* _internal_mutable_server_type();
  public:

  // string FileName = 4;
  void clear_filename();
  const std::string& filename() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_filename(ArgT0&& arg0, ArgT... args);
  std::string* mutable_filename();
  PROTOBUF_NODISCARD std::string* release_filename();
  void set_allocated_filename(std::string* filename);
  private:
  const std::string& _internal_filename() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filename(const std::string& value);
  std::string* _internal_mutable_filename();
  public:

  // string StrMsg = 5;
  void clear_strmsg();
  const std::string& strmsg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_strmsg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_strmsg();
  PROTOBUF_NODISCARD std::string* release_strmsg();
  void set_allocated_strmsg(std::string* strmsg);
  private:
  const std::string& _internal_strmsg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_strmsg(const std::string& value);
  std::string* _internal_mutable_strmsg();
  public:

  // uint32 sTID = 2;
  void clear_stid();
  uint32_t stid() const;
  void set_stid(uint32_t value);
  private:
  uint32_t _internal_stid() const;
  void _internal_set_stid(uint32_t value);
  public:

  // uint32 dTID = 3;
  void clear_dtid();
  uint32_t dtid() const;
  void set_dtid(uint32_t value);
  private:
  uint32_t _internal_dtid() const;
  void _internal_set_dtid(uint32_t value);
  public:

  // uint64 intMsg = 6;
  void clear_intmsg();
  uint64_t intmsg() const;
  void set_intmsg(uint64_t value);
  private:
  uint64_t _internal_intmsg() const;
  void _internal_set_intmsg(uint64_t value);
  public:

  // double dblMsg = 7;
  void clear_dblmsg();
  double dblmsg() const;
  void set_dblmsg(double value);
  private:
  double _internal_dblmsg() const;
  void _internal_set_dblmsg(double value);
  public:

  // @@protoc_insertion_point(class_scope:hh.RecvFinishMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr server_type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filename_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr strmsg_;
    uint32_t stid_;
    uint32_t dtid_;
    uint64_t intmsg_;
    double dblmsg_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_FileBlockMsg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FileBlockMsg

// string server_type = 1;
inline void FileBlockMsg::clear_server_type() {
  _impl_.server_type_.ClearToEmpty();
}
inline const std::string& FileBlockMsg::server_type() const {
  // @@protoc_insertion_point(field_get:hh.FileBlockMsg.server_type)
  return _internal_server_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileBlockMsg::set_server_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.server_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hh.FileBlockMsg.server_type)
}
inline std::string* FileBlockMsg::mutable_server_type() {
  std::string* _s = _internal_mutable_server_type();
  // @@protoc_insertion_point(field_mutable:hh.FileBlockMsg.server_type)
  return _s;
}
inline const std::string& FileBlockMsg::_internal_server_type() const {
  return _impl_.server_type_.Get();
}
inline void FileBlockMsg::_internal_set_server_type(const std::string& value) {
  
  _impl_.server_type_.Set(value, GetArenaForAllocation());
}
inline std::string* FileBlockMsg::_internal_mutable_server_type() {
  
  return _impl_.server_type_.Mutable(GetArenaForAllocation());
}
inline std::string* FileBlockMsg::release_server_type() {
  // @@protoc_insertion_point(field_release:hh.FileBlockMsg.server_type)
  return _impl_.server_type_.Release();
}
inline void FileBlockMsg::set_allocated_server_type(std::string* server_type) {
  if (server_type != nullptr) {
    
  } else {
    
  }
  _impl_.server_type_.SetAllocated(server_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.server_type_.IsDefault()) {
    _impl_.server_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hh.FileBlockMsg.server_type)
}

// uint32 sTID = 2;
inline void FileBlockMsg::clear_stid() {
  _impl_.stid_ = 0u;
}
inline uint32_t FileBlockMsg::_internal_stid() const {
  return _impl_.stid_;
}
inline uint32_t FileBlockMsg::stid() const {
  // @@protoc_insertion_point(field_get:hh.FileBlockMsg.sTID)
  return _internal_stid();
}
inline void FileBlockMsg::_internal_set_stid(uint32_t value) {
  
  _impl_.stid_ = value;
}
inline void FileBlockMsg::set_stid(uint32_t value) {
  _internal_set_stid(value);
  // @@protoc_insertion_point(field_set:hh.FileBlockMsg.sTID)
}

// uint32 dTID = 3;
inline void FileBlockMsg::clear_dtid() {
  _impl_.dtid_ = 0u;
}
inline uint32_t FileBlockMsg::_internal_dtid() const {
  return _impl_.dtid_;
}
inline uint32_t FileBlockMsg::dtid() const {
  // @@protoc_insertion_point(field_get:hh.FileBlockMsg.dTID)
  return _internal_dtid();
}
inline void FileBlockMsg::_internal_set_dtid(uint32_t value) {
  
  _impl_.dtid_ = value;
}
inline void FileBlockMsg::set_dtid(uint32_t value) {
  _internal_set_dtid(value);
  // @@protoc_insertion_point(field_set:hh.FileBlockMsg.dTID)
}

// uint32 FileID_ = 4;
inline void FileBlockMsg::clear_fileid_() {
  _impl_.fileid__ = 0u;
}
inline uint32_t FileBlockMsg::_internal_fileid_() const {
  return _impl_.fileid__;
}
inline uint32_t FileBlockMsg::fileid_() const {
  // @@protoc_insertion_point(field_get:hh.FileBlockMsg.FileID_)
  return _internal_fileid_();
}
inline void FileBlockMsg::_internal_set_fileid_(uint32_t value) {
  
  _impl_.fileid__ = value;
}
inline void FileBlockMsg::set_fileid_(uint32_t value) {
  _internal_set_fileid_(value);
  // @@protoc_insertion_point(field_set:hh.FileBlockMsg.FileID_)
}

// uint64 FileBlockNumber_ = 5;
inline void FileBlockMsg::clear_fileblocknumber_() {
  _impl_.fileblocknumber__ = uint64_t{0u};
}
inline uint64_t FileBlockMsg::_internal_fileblocknumber_() const {
  return _impl_.fileblocknumber__;
}
inline uint64_t FileBlockMsg::fileblocknumber_() const {
  // @@protoc_insertion_point(field_get:hh.FileBlockMsg.FileBlockNumber_)
  return _internal_fileblocknumber_();
}
inline void FileBlockMsg::_internal_set_fileblocknumber_(uint64_t value) {
  
  _impl_.fileblocknumber__ = value;
}
inline void FileBlockMsg::set_fileblocknumber_(uint64_t value) {
  _internal_set_fileblocknumber_(value);
  // @@protoc_insertion_point(field_set:hh.FileBlockMsg.FileBlockNumber_)
}

// uint64 FileBlockNumber_total_ = 6;
inline void FileBlockMsg::clear_fileblocknumber_total_() {
  _impl_.fileblocknumber_total__ = uint64_t{0u};
}
inline uint64_t FileBlockMsg::_internal_fileblocknumber_total_() const {
  return _impl_.fileblocknumber_total__;
}
inline uint64_t FileBlockMsg::fileblocknumber_total_() const {
  // @@protoc_insertion_point(field_get:hh.FileBlockMsg.FileBlockNumber_total_)
  return _internal_fileblocknumber_total_();
}
inline void FileBlockMsg::_internal_set_fileblocknumber_total_(uint64_t value) {
  
  _impl_.fileblocknumber_total__ = value;
}
inline void FileBlockMsg::set_fileblocknumber_total_(uint64_t value) {
  _internal_set_fileblocknumber_total_(value);
  // @@protoc_insertion_point(field_set:hh.FileBlockMsg.FileBlockNumber_total_)
}

// uint64 FileBlockSize_ = 7;
inline void FileBlockMsg::clear_fileblocksize_() {
  _impl_.fileblocksize__ = uint64_t{0u};
}
inline uint64_t FileBlockMsg::_internal_fileblocksize_() const {
  return _impl_.fileblocksize__;
}
inline uint64_t FileBlockMsg::fileblocksize_() const {
  // @@protoc_insertion_point(field_get:hh.FileBlockMsg.FileBlockSize_)
  return _internal_fileblocksize_();
}
inline void FileBlockMsg::_internal_set_fileblocksize_(uint64_t value) {
  
  _impl_.fileblocksize__ = value;
}
inline void FileBlockMsg::set_fileblocksize_(uint64_t value) {
  _internal_set_fileblocksize_(value);
  // @@protoc_insertion_point(field_set:hh.FileBlockMsg.FileBlockSize_)
}

// uint64 FileSize_total_ = 8;
inline void FileBlockMsg::clear_filesize_total_() {
  _impl_.filesize_total__ = uint64_t{0u};
}
inline uint64_t FileBlockMsg::_internal_filesize_total_() const {
  return _impl_.filesize_total__;
}
inline uint64_t FileBlockMsg::filesize_total_() const {
  // @@protoc_insertion_point(field_get:hh.FileBlockMsg.FileSize_total_)
  return _internal_filesize_total_();
}
inline void FileBlockMsg::_internal_set_filesize_total_(uint64_t value) {
  
  _impl_.filesize_total__ = value;
}
inline void FileBlockMsg::set_filesize_total_(uint64_t value) {
  _internal_set_filesize_total_(value);
  // @@protoc_insertion_point(field_set:hh.FileBlockMsg.FileSize_total_)
}

// string FileName_ = 9;
inline void FileBlockMsg::clear_filename_() {
  _impl_.filename__.ClearToEmpty();
}
inline const std::string& FileBlockMsg::filename_() const {
  // @@protoc_insertion_point(field_get:hh.FileBlockMsg.FileName_)
  return _internal_filename_();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileBlockMsg::set_filename_(ArgT0&& arg0, ArgT... args) {
 
 _impl_.filename__.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hh.FileBlockMsg.FileName_)
}
inline std::string* FileBlockMsg::mutable_filename_() {
  std::string* _s = _internal_mutable_filename_();
  // @@protoc_insertion_point(field_mutable:hh.FileBlockMsg.FileName_)
  return _s;
}
inline const std::string& FileBlockMsg::_internal_filename_() const {
  return _impl_.filename__.Get();
}
inline void FileBlockMsg::_internal_set_filename_(const std::string& value) {
  
  _impl_.filename__.Set(value, GetArenaForAllocation());
}
inline std::string* FileBlockMsg::_internal_mutable_filename_() {
  
  return _impl_.filename__.Mutable(GetArenaForAllocation());
}
inline std::string* FileBlockMsg::release_filename_() {
  // @@protoc_insertion_point(field_release:hh.FileBlockMsg.FileName_)
  return _impl_.filename__.Release();
}
inline void FileBlockMsg::set_allocated_filename_(std::string* filename_) {
  if (filename_ != nullptr) {
    
  } else {
    
  }
  _impl_.filename__.SetAllocated(filename_, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.filename__.IsDefault()) {
    _impl_.filename__.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hh.FileBlockMsg.FileName_)
}

// bytes FileBlockBuffer_ = 10;
inline void FileBlockMsg::clear_fileblockbuffer_() {
  _impl_.fileblockbuffer__.ClearToEmpty();
}
inline const std::string& FileBlockMsg::fileblockbuffer_() const {
  // @@protoc_insertion_point(field_get:hh.FileBlockMsg.FileBlockBuffer_)
  return _internal_fileblockbuffer_();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileBlockMsg::set_fileblockbuffer_(ArgT0&& arg0, ArgT... args) {
 
 _impl_.fileblockbuffer__.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hh.FileBlockMsg.FileBlockBuffer_)
}
inline std::string* FileBlockMsg::mutable_fileblockbuffer_() {
  std::string* _s = _internal_mutable_fileblockbuffer_();
  // @@protoc_insertion_point(field_mutable:hh.FileBlockMsg.FileBlockBuffer_)
  return _s;
}
inline const std::string& FileBlockMsg::_internal_fileblockbuffer_() const {
  return _impl_.fileblockbuffer__.Get();
}
inline void FileBlockMsg::_internal_set_fileblockbuffer_(const std::string& value) {
  
  _impl_.fileblockbuffer__.Set(value, GetArenaForAllocation());
}
inline std::string* FileBlockMsg::_internal_mutable_fileblockbuffer_() {
  
  return _impl_.fileblockbuffer__.Mutable(GetArenaForAllocation());
}
inline std::string* FileBlockMsg::release_fileblockbuffer_() {
  // @@protoc_insertion_point(field_release:hh.FileBlockMsg.FileBlockBuffer_)
  return _impl_.fileblockbuffer__.Release();
}
inline void FileBlockMsg::set_allocated_fileblockbuffer_(std::string* fileblockbuffer_) {
  if (fileblockbuffer_ != nullptr) {
    
  } else {
    
  }
  _impl_.fileblockbuffer__.SetAllocated(fileblockbuffer_, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.fileblockbuffer__.IsDefault()) {
    _impl_.fileblockbuffer__.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hh.FileBlockMsg.FileBlockBuffer_)
}

// -------------------------------------------------------------------

// RecvFinishMsg

// string server_type = 1;
inline void RecvFinishMsg::clear_server_type() {
  _impl_.server_type_.ClearToEmpty();
}
inline const std::string& RecvFinishMsg::server_type() const {
  // @@protoc_insertion_point(field_get:hh.RecvFinishMsg.server_type)
  return _internal_server_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RecvFinishMsg::set_server_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.server_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hh.RecvFinishMsg.server_type)
}
inline std::string* RecvFinishMsg::mutable_server_type() {
  std::string* _s = _internal_mutable_server_type();
  // @@protoc_insertion_point(field_mutable:hh.RecvFinishMsg.server_type)
  return _s;
}
inline const std::string& RecvFinishMsg::_internal_server_type() const {
  return _impl_.server_type_.Get();
}
inline void RecvFinishMsg::_internal_set_server_type(const std::string& value) {
  
  _impl_.server_type_.Set(value, GetArenaForAllocation());
}
inline std::string* RecvFinishMsg::_internal_mutable_server_type() {
  
  return _impl_.server_type_.Mutable(GetArenaForAllocation());
}
inline std::string* RecvFinishMsg::release_server_type() {
  // @@protoc_insertion_point(field_release:hh.RecvFinishMsg.server_type)
  return _impl_.server_type_.Release();
}
inline void RecvFinishMsg::set_allocated_server_type(std::string* server_type) {
  if (server_type != nullptr) {
    
  } else {
    
  }
  _impl_.server_type_.SetAllocated(server_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.server_type_.IsDefault()) {
    _impl_.server_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hh.RecvFinishMsg.server_type)
}

// uint32 sTID = 2;
inline void RecvFinishMsg::clear_stid() {
  _impl_.stid_ = 0u;
}
inline uint32_t RecvFinishMsg::_internal_stid() const {
  return _impl_.stid_;
}
inline uint32_t RecvFinishMsg::stid() const {
  // @@protoc_insertion_point(field_get:hh.RecvFinishMsg.sTID)
  return _internal_stid();
}
inline void RecvFinishMsg::_internal_set_stid(uint32_t value) {
  
  _impl_.stid_ = value;
}
inline void RecvFinishMsg::set_stid(uint32_t value) {
  _internal_set_stid(value);
  // @@protoc_insertion_point(field_set:hh.RecvFinishMsg.sTID)
}

// uint32 dTID = 3;
inline void RecvFinishMsg::clear_dtid() {
  _impl_.dtid_ = 0u;
}
inline uint32_t RecvFinishMsg::_internal_dtid() const {
  return _impl_.dtid_;
}
inline uint32_t RecvFinishMsg::dtid() const {
  // @@protoc_insertion_point(field_get:hh.RecvFinishMsg.dTID)
  return _internal_dtid();
}
inline void RecvFinishMsg::_internal_set_dtid(uint32_t value) {
  
  _impl_.dtid_ = value;
}
inline void RecvFinishMsg::set_dtid(uint32_t value) {
  _internal_set_dtid(value);
  // @@protoc_insertion_point(field_set:hh.RecvFinishMsg.dTID)
}

// string FileName = 4;
inline void RecvFinishMsg::clear_filename() {
  _impl_.filename_.ClearToEmpty();
}
inline const std::string& RecvFinishMsg::filename() const {
  // @@protoc_insertion_point(field_get:hh.RecvFinishMsg.FileName)
  return _internal_filename();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RecvFinishMsg::set_filename(ArgT0&& arg0, ArgT... args) {
 
 _impl_.filename_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hh.RecvFinishMsg.FileName)
}
inline std::string* RecvFinishMsg::mutable_filename() {
  std::string* _s = _internal_mutable_filename();
  // @@protoc_insertion_point(field_mutable:hh.RecvFinishMsg.FileName)
  return _s;
}
inline const std::string& RecvFinishMsg::_internal_filename() const {
  return _impl_.filename_.Get();
}
inline void RecvFinishMsg::_internal_set_filename(const std::string& value) {
  
  _impl_.filename_.Set(value, GetArenaForAllocation());
}
inline std::string* RecvFinishMsg::_internal_mutable_filename() {
  
  return _impl_.filename_.Mutable(GetArenaForAllocation());
}
inline std::string* RecvFinishMsg::release_filename() {
  // @@protoc_insertion_point(field_release:hh.RecvFinishMsg.FileName)
  return _impl_.filename_.Release();
}
inline void RecvFinishMsg::set_allocated_filename(std::string* filename) {
  if (filename != nullptr) {
    
  } else {
    
  }
  _impl_.filename_.SetAllocated(filename, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.filename_.IsDefault()) {
    _impl_.filename_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hh.RecvFinishMsg.FileName)
}

// string StrMsg = 5;
inline void RecvFinishMsg::clear_strmsg() {
  _impl_.strmsg_.ClearToEmpty();
}
inline const std::string& RecvFinishMsg::strmsg() const {
  // @@protoc_insertion_point(field_get:hh.RecvFinishMsg.StrMsg)
  return _internal_strmsg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RecvFinishMsg::set_strmsg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.strmsg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hh.RecvFinishMsg.StrMsg)
}
inline std::string* RecvFinishMsg::mutable_strmsg() {
  std::string* _s = _internal_mutable_strmsg();
  // @@protoc_insertion_point(field_mutable:hh.RecvFinishMsg.StrMsg)
  return _s;
}
inline const std::string& RecvFinishMsg::_internal_strmsg() const {
  return _impl_.strmsg_.Get();
}
inline void RecvFinishMsg::_internal_set_strmsg(const std::string& value) {
  
  _impl_.strmsg_.Set(value, GetArenaForAllocation());
}
inline std::string* RecvFinishMsg::_internal_mutable_strmsg() {
  
  return _impl_.strmsg_.Mutable(GetArenaForAllocation());
}
inline std::string* RecvFinishMsg::release_strmsg() {
  // @@protoc_insertion_point(field_release:hh.RecvFinishMsg.StrMsg)
  return _impl_.strmsg_.Release();
}
inline void RecvFinishMsg::set_allocated_strmsg(std::string* strmsg) {
  if (strmsg != nullptr) {
    
  } else {
    
  }
  _impl_.strmsg_.SetAllocated(strmsg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.strmsg_.IsDefault()) {
    _impl_.strmsg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hh.RecvFinishMsg.StrMsg)
}

// uint64 intMsg = 6;
inline void RecvFinishMsg::clear_intmsg() {
  _impl_.intmsg_ = uint64_t{0u};
}
inline uint64_t RecvFinishMsg::_internal_intmsg() const {
  return _impl_.intmsg_;
}
inline uint64_t RecvFinishMsg::intmsg() const {
  // @@protoc_insertion_point(field_get:hh.RecvFinishMsg.intMsg)
  return _internal_intmsg();
}
inline void RecvFinishMsg::_internal_set_intmsg(uint64_t value) {
  
  _impl_.intmsg_ = value;
}
inline void RecvFinishMsg::set_intmsg(uint64_t value) {
  _internal_set_intmsg(value);
  // @@protoc_insertion_point(field_set:hh.RecvFinishMsg.intMsg)
}

// double dblMsg = 7;
inline void RecvFinishMsg::clear_dblmsg() {
  _impl_.dblmsg_ = 0;
}
inline double RecvFinishMsg::_internal_dblmsg() const {
  return _impl_.dblmsg_;
}
inline double RecvFinishMsg::dblmsg() const {
  // @@protoc_insertion_point(field_get:hh.RecvFinishMsg.dblMsg)
  return _internal_dblmsg();
}
inline void RecvFinishMsg::_internal_set_dblmsg(double value) {
  
  _impl_.dblmsg_ = value;
}
inline void RecvFinishMsg::set_dblmsg(double value) {
  _internal_set_dblmsg(value);
  // @@protoc_insertion_point(field_set:hh.RecvFinishMsg.dblMsg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace hh

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_FileBlockMsg_2eproto
