// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#ifndef PROTOBUF_INCLUDED_msg_2eproto
#define PROTOBUF_INCLUDED_msg_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_msg_2eproto 

namespace protobuf_msg_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_msg_2eproto
namespace msg {
class msg_a;
class msg_aDefaultTypeInternal;
extern msg_aDefaultTypeInternal _msg_a_default_instance_;
class msg_b;
class msg_bDefaultTypeInternal;
extern msg_bDefaultTypeInternal _msg_b_default_instance_;
class msg_head;
class msg_headDefaultTypeInternal;
extern msg_headDefaultTypeInternal _msg_head_default_instance_;
}  // namespace msg
namespace google {
namespace protobuf {
template<> ::msg::msg_a* Arena::CreateMaybeMessage<::msg::msg_a>(Arena*);
template<> ::msg::msg_b* Arena::CreateMaybeMessage<::msg::msg_b>(Arena*);
template<> ::msg::msg_head* Arena::CreateMaybeMessage<::msg::msg_head>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace msg {

// ===================================================================

class msg_head : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:msg.msg_head) */ {
 public:
  msg_head();
  virtual ~msg_head();

  msg_head(const msg_head& from);

  inline msg_head& operator=(const msg_head& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  msg_head(msg_head&& from) noexcept
    : msg_head() {
    *this = ::std::move(from);
  }

  inline msg_head& operator=(msg_head&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const msg_head& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const msg_head* internal_default_instance() {
    return reinterpret_cast<const msg_head*>(
               &_msg_head_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(msg_head* other);
  friend void swap(msg_head& a, msg_head& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline msg_head* New() const final {
    return CreateMaybeMessage<msg_head>(NULL);
  }

  msg_head* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<msg_head>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const msg_head& from);
  void MergeFrom(const msg_head& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(msg_head* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string server_type = 1;
  void clear_server_type();
  static const int kServerTypeFieldNumber = 1;
  const ::std::string& server_type() const;
  void set_server_type(const ::std::string& value);
  #if LANG_CXX11
  void set_server_type(::std::string&& value);
  #endif
  void set_server_type(const char* value);
  void set_server_type(const char* value, size_t size);
  ::std::string* mutable_server_type();
  ::std::string* release_server_type();
  void set_allocated_server_type(::std::string* server_type);

  // @@protoc_insertion_point(class_scope:msg.msg_head)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr server_type_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_msg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class msg_a : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:msg.msg_a) */ {
 public:
  msg_a();
  virtual ~msg_a();

  msg_a(const msg_a& from);

  inline msg_a& operator=(const msg_a& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  msg_a(msg_a&& from) noexcept
    : msg_a() {
    *this = ::std::move(from);
  }

  inline msg_a& operator=(msg_a&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const msg_a& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const msg_a* internal_default_instance() {
    return reinterpret_cast<const msg_a*>(
               &_msg_a_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(msg_a* other);
  friend void swap(msg_a& a, msg_a& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline msg_a* New() const final {
    return CreateMaybeMessage<msg_a>(NULL);
  }

  msg_a* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<msg_a>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const msg_a& from);
  void MergeFrom(const msg_a& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(msg_a* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string server_type = 1;
  void clear_server_type();
  static const int kServerTypeFieldNumber = 1;
  const ::std::string& server_type() const;
  void set_server_type(const ::std::string& value);
  #if LANG_CXX11
  void set_server_type(::std::string&& value);
  #endif
  void set_server_type(const char* value);
  void set_server_type(const char* value, size_t size);
  ::std::string* mutable_server_type();
  ::std::string* release_server_type();
  void set_allocated_server_type(::std::string* server_type);

  // string time = 3;
  void clear_time();
  static const int kTimeFieldNumber = 3;
  const ::std::string& time() const;
  void set_time(const ::std::string& value);
  #if LANG_CXX11
  void set_time(::std::string&& value);
  #endif
  void set_time(const char* value);
  void set_time(const char* value, size_t size);
  ::std::string* mutable_time();
  ::std::string* release_time();
  void set_allocated_time(::std::string* time);

  // int32 id = 2;
  void clear_id();
  static const int kIdFieldNumber = 2;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:msg.msg_a)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr server_type_;
  ::google::protobuf::internal::ArenaStringPtr time_;
  ::google::protobuf::int32 id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_msg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class msg_b : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:msg.msg_b) */ {
 public:
  msg_b();
  virtual ~msg_b();

  msg_b(const msg_b& from);

  inline msg_b& operator=(const msg_b& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  msg_b(msg_b&& from) noexcept
    : msg_b() {
    *this = ::std::move(from);
  }

  inline msg_b& operator=(msg_b&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const msg_b& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const msg_b* internal_default_instance() {
    return reinterpret_cast<const msg_b*>(
               &_msg_b_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(msg_b* other);
  friend void swap(msg_b& a, msg_b& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline msg_b* New() const final {
    return CreateMaybeMessage<msg_b>(NULL);
  }

  msg_b* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<msg_b>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const msg_b& from);
  void MergeFrom(const msg_b& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(msg_b* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string server_type = 1;
  void clear_server_type();
  static const int kServerTypeFieldNumber = 1;
  const ::std::string& server_type() const;
  void set_server_type(const ::std::string& value);
  #if LANG_CXX11
  void set_server_type(::std::string&& value);
  #endif
  void set_server_type(const char* value);
  void set_server_type(const char* value, size_t size);
  ::std::string* mutable_server_type();
  ::std::string* release_server_type();
  void set_allocated_server_type(::std::string* server_type);

  // string time = 3;
  void clear_time();
  static const int kTimeFieldNumber = 3;
  const ::std::string& time() const;
  void set_time(const ::std::string& value);
  #if LANG_CXX11
  void set_time(::std::string&& value);
  #endif
  void set_time(const char* value);
  void set_time(const char* value, size_t size);
  ::std::string* mutable_time();
  ::std::string* release_time();
  void set_allocated_time(::std::string* time);

  // int32 id = 2;
  void clear_id();
  static const int kIdFieldNumber = 2;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:msg.msg_b)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr server_type_;
  ::google::protobuf::internal::ArenaStringPtr time_;
  ::google::protobuf::int32 id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_msg_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// msg_head

// string server_type = 1;
inline void msg_head::clear_server_type() {
  server_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& msg_head::server_type() const {
  // @@protoc_insertion_point(field_get:msg.msg_head.server_type)
  return server_type_.GetNoArena();
}
inline void msg_head::set_server_type(const ::std::string& value) {
  
  server_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:msg.msg_head.server_type)
}
#if LANG_CXX11
inline void msg_head::set_server_type(::std::string&& value) {
  
  server_type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:msg.msg_head.server_type)
}
#endif
inline void msg_head::set_server_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  server_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:msg.msg_head.server_type)
}
inline void msg_head::set_server_type(const char* value, size_t size) {
  
  server_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:msg.msg_head.server_type)
}
inline ::std::string* msg_head::mutable_server_type() {
  
  // @@protoc_insertion_point(field_mutable:msg.msg_head.server_type)
  return server_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* msg_head::release_server_type() {
  // @@protoc_insertion_point(field_release:msg.msg_head.server_type)
  
  return server_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void msg_head::set_allocated_server_type(::std::string* server_type) {
  if (server_type != NULL) {
    
  } else {
    
  }
  server_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), server_type);
  // @@protoc_insertion_point(field_set_allocated:msg.msg_head.server_type)
}

// -------------------------------------------------------------------

// msg_a

// string server_type = 1;
inline void msg_a::clear_server_type() {
  server_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& msg_a::server_type() const {
  // @@protoc_insertion_point(field_get:msg.msg_a.server_type)
  return server_type_.GetNoArena();
}
inline void msg_a::set_server_type(const ::std::string& value) {
  
  server_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:msg.msg_a.server_type)
}
#if LANG_CXX11
inline void msg_a::set_server_type(::std::string&& value) {
  
  server_type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:msg.msg_a.server_type)
}
#endif
inline void msg_a::set_server_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  server_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:msg.msg_a.server_type)
}
inline void msg_a::set_server_type(const char* value, size_t size) {
  
  server_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:msg.msg_a.server_type)
}
inline ::std::string* msg_a::mutable_server_type() {
  
  // @@protoc_insertion_point(field_mutable:msg.msg_a.server_type)
  return server_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* msg_a::release_server_type() {
  // @@protoc_insertion_point(field_release:msg.msg_a.server_type)
  
  return server_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void msg_a::set_allocated_server_type(::std::string* server_type) {
  if (server_type != NULL) {
    
  } else {
    
  }
  server_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), server_type);
  // @@protoc_insertion_point(field_set_allocated:msg.msg_a.server_type)
}

// int32 id = 2;
inline void msg_a::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 msg_a::id() const {
  // @@protoc_insertion_point(field_get:msg.msg_a.id)
  return id_;
}
inline void msg_a::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:msg.msg_a.id)
}

// string time = 3;
inline void msg_a::clear_time() {
  time_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& msg_a::time() const {
  // @@protoc_insertion_point(field_get:msg.msg_a.time)
  return time_.GetNoArena();
}
inline void msg_a::set_time(const ::std::string& value) {
  
  time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:msg.msg_a.time)
}
#if LANG_CXX11
inline void msg_a::set_time(::std::string&& value) {
  
  time_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:msg.msg_a.time)
}
#endif
inline void msg_a::set_time(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:msg.msg_a.time)
}
inline void msg_a::set_time(const char* value, size_t size) {
  
  time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:msg.msg_a.time)
}
inline ::std::string* msg_a::mutable_time() {
  
  // @@protoc_insertion_point(field_mutable:msg.msg_a.time)
  return time_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* msg_a::release_time() {
  // @@protoc_insertion_point(field_release:msg.msg_a.time)
  
  return time_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void msg_a::set_allocated_time(::std::string* time) {
  if (time != NULL) {
    
  } else {
    
  }
  time_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), time);
  // @@protoc_insertion_point(field_set_allocated:msg.msg_a.time)
}

// -------------------------------------------------------------------

// msg_b

// string server_type = 1;
inline void msg_b::clear_server_type() {
  server_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& msg_b::server_type() const {
  // @@protoc_insertion_point(field_get:msg.msg_b.server_type)
  return server_type_.GetNoArena();
}
inline void msg_b::set_server_type(const ::std::string& value) {
  
  server_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:msg.msg_b.server_type)
}
#if LANG_CXX11
inline void msg_b::set_server_type(::std::string&& value) {
  
  server_type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:msg.msg_b.server_type)
}
#endif
inline void msg_b::set_server_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  server_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:msg.msg_b.server_type)
}
inline void msg_b::set_server_type(const char* value, size_t size) {
  
  server_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:msg.msg_b.server_type)
}
inline ::std::string* msg_b::mutable_server_type() {
  
  // @@protoc_insertion_point(field_mutable:msg.msg_b.server_type)
  return server_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* msg_b::release_server_type() {
  // @@protoc_insertion_point(field_release:msg.msg_b.server_type)
  
  return server_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void msg_b::set_allocated_server_type(::std::string* server_type) {
  if (server_type != NULL) {
    
  } else {
    
  }
  server_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), server_type);
  // @@protoc_insertion_point(field_set_allocated:msg.msg_b.server_type)
}

// int32 id = 2;
inline void msg_b::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 msg_b::id() const {
  // @@protoc_insertion_point(field_get:msg.msg_b.id)
  return id_;
}
inline void msg_b::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:msg.msg_b.id)
}

// string time = 3;
inline void msg_b::clear_time() {
  time_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& msg_b::time() const {
  // @@protoc_insertion_point(field_get:msg.msg_b.time)
  return time_.GetNoArena();
}
inline void msg_b::set_time(const ::std::string& value) {
  
  time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:msg.msg_b.time)
}
#if LANG_CXX11
inline void msg_b::set_time(::std::string&& value) {
  
  time_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:msg.msg_b.time)
}
#endif
inline void msg_b::set_time(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:msg.msg_b.time)
}
inline void msg_b::set_time(const char* value, size_t size) {
  
  time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:msg.msg_b.time)
}
inline ::std::string* msg_b::mutable_time() {
  
  // @@protoc_insertion_point(field_mutable:msg.msg_b.time)
  return time_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* msg_b::release_time() {
  // @@protoc_insertion_point(field_release:msg.msg_b.time)
  
  return time_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void msg_b::set_allocated_time(::std::string* time) {
  if (time != NULL) {
    
  } else {
    
  }
  time_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), time);
  // @@protoc_insertion_point(field_set_allocated:msg.msg_b.time)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace msg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_msg_2eproto
