// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_msg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_msg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_msg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_msg_2eproto;
namespace msg {
class msg_a;
struct msg_aDefaultTypeInternal;
extern msg_aDefaultTypeInternal _msg_a_default_instance_;
class msg_b;
struct msg_bDefaultTypeInternal;
extern msg_bDefaultTypeInternal _msg_b_default_instance_;
class msg_head;
struct msg_headDefaultTypeInternal;
extern msg_headDefaultTypeInternal _msg_head_default_instance_;
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> ::msg::msg_a* Arena::CreateMaybeMessage<::msg::msg_a>(Arena*);
template<> ::msg::msg_b* Arena::CreateMaybeMessage<::msg::msg_b>(Arena*);
template<> ::msg::msg_head* Arena::CreateMaybeMessage<::msg::msg_head>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace msg {

// ===================================================================

class msg_head final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.msg_head) */ {
 public:
  inline msg_head() : msg_head(nullptr) {}
  ~msg_head() override;
  explicit PROTOBUF_CONSTEXPR msg_head(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  msg_head(const msg_head& from);
  msg_head(msg_head&& from) noexcept
    : msg_head() {
    *this = ::std::move(from);
  }

  inline msg_head& operator=(const msg_head& from) {
    CopyFrom(from);
    return *this;
  }
  inline msg_head& operator=(msg_head&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const msg_head& default_instance() {
    return *internal_default_instance();
  }
  static inline const msg_head* internal_default_instance() {
    return reinterpret_cast<const msg_head*>(
               &_msg_head_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(msg_head& a, msg_head& b) {
    a.Swap(&b);
  }
  inline void Swap(msg_head* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(msg_head* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  msg_head* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<msg_head>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const msg_head& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const msg_head& from) {
    msg_head::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(msg_head* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.msg_head";
  }
  protected:
  explicit msg_head(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServerTypeFieldNumber = 1,
  };
  // string server_type = 1;
  void clear_server_type();
  const std::string& server_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_server_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_server_type();
  PROTOBUF_NODISCARD std::string* release_server_type();
  void set_allocated_server_type(std::string* server_type);
  private:
  const std::string& _internal_server_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_server_type(const std::string& value);
  std::string* _internal_mutable_server_type();
  public:

  // @@protoc_insertion_point(class_scope:msg.msg_head)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr server_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_2eproto;
};
// -------------------------------------------------------------------

class msg_a final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.msg_a) */ {
 public:
  inline msg_a() : msg_a(nullptr) {}
  ~msg_a() override;
  explicit PROTOBUF_CONSTEXPR msg_a(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  msg_a(const msg_a& from);
  msg_a(msg_a&& from) noexcept
    : msg_a() {
    *this = ::std::move(from);
  }

  inline msg_a& operator=(const msg_a& from) {
    CopyFrom(from);
    return *this;
  }
  inline msg_a& operator=(msg_a&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const msg_a& default_instance() {
    return *internal_default_instance();
  }
  static inline const msg_a* internal_default_instance() {
    return reinterpret_cast<const msg_a*>(
               &_msg_a_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(msg_a& a, msg_a& b) {
    a.Swap(&b);
  }
  inline void Swap(msg_a* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(msg_a* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  msg_a* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<msg_a>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const msg_a& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const msg_a& from) {
    msg_a::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(msg_a* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.msg_a";
  }
  protected:
  explicit msg_a(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServerTypeFieldNumber = 1,
    kTimeFieldNumber = 3,
    kDataFieldNumber = 4,
    kIdFieldNumber = 2,
  };
  // string server_type = 1;
  void clear_server_type();
  const std::string& server_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_server_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_server_type();
  PROTOBUF_NODISCARD std::string* release_server_type();
  void set_allocated_server_type(std::string* server_type);
  private:
  const std::string& _internal_server_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_server_type(const std::string& value);
  std::string* _internal_mutable_server_type();
  public:

  // string time = 3;
  void clear_time();
  const std::string& time() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_time(ArgT0&& arg0, ArgT... args);
  std::string* mutable_time();
  PROTOBUF_NODISCARD std::string* release_time();
  void set_allocated_time(std::string* time);
  private:
  const std::string& _internal_time() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_time(const std::string& value);
  std::string* _internal_mutable_time();
  public:

  // string data = 4;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // int32 id = 2;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:msg.msg_a)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr server_type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr time_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
    int32_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_2eproto;
};
// -------------------------------------------------------------------

class msg_b final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.msg_b) */ {
 public:
  inline msg_b() : msg_b(nullptr) {}
  ~msg_b() override;
  explicit PROTOBUF_CONSTEXPR msg_b(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  msg_b(const msg_b& from);
  msg_b(msg_b&& from) noexcept
    : msg_b() {
    *this = ::std::move(from);
  }

  inline msg_b& operator=(const msg_b& from) {
    CopyFrom(from);
    return *this;
  }
  inline msg_b& operator=(msg_b&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const msg_b& default_instance() {
    return *internal_default_instance();
  }
  static inline const msg_b* internal_default_instance() {
    return reinterpret_cast<const msg_b*>(
               &_msg_b_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(msg_b& a, msg_b& b) {
    a.Swap(&b);
  }
  inline void Swap(msg_b* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(msg_b* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  msg_b* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<msg_b>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const msg_b& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const msg_b& from) {
    msg_b::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(msg_b* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.msg_b";
  }
  protected:
  explicit msg_b(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServerTypeFieldNumber = 1,
    kTimeFieldNumber = 3,
    kIdFieldNumber = 2,
  };
  // string server_type = 1;
  void clear_server_type();
  const std::string& server_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_server_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_server_type();
  PROTOBUF_NODISCARD std::string* release_server_type();
  void set_allocated_server_type(std::string* server_type);
  private:
  const std::string& _internal_server_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_server_type(const std::string& value);
  std::string* _internal_mutable_server_type();
  public:

  // string time = 3;
  void clear_time();
  const std::string& time() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_time(ArgT0&& arg0, ArgT... args);
  std::string* mutable_time();
  PROTOBUF_NODISCARD std::string* release_time();
  void set_allocated_time(std::string* time);
  private:
  const std::string& _internal_time() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_time(const std::string& value);
  std::string* _internal_mutable_time();
  public:

  // int32 id = 2;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:msg.msg_b)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr server_type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr time_;
    int32_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// msg_head

// string server_type = 1;
inline void msg_head::clear_server_type() {
  _impl_.server_type_.ClearToEmpty();
}
inline const std::string& msg_head::server_type() const {
  // @@protoc_insertion_point(field_get:msg.msg_head.server_type)
  return _internal_server_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_head::set_server_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.server_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.msg_head.server_type)
}
inline std::string* msg_head::mutable_server_type() {
  std::string* _s = _internal_mutable_server_type();
  // @@protoc_insertion_point(field_mutable:msg.msg_head.server_type)
  return _s;
}
inline const std::string& msg_head::_internal_server_type() const {
  return _impl_.server_type_.Get();
}
inline void msg_head::_internal_set_server_type(const std::string& value) {
  
  _impl_.server_type_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_head::_internal_mutable_server_type() {
  
  return _impl_.server_type_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_head::release_server_type() {
  // @@protoc_insertion_point(field_release:msg.msg_head.server_type)
  return _impl_.server_type_.Release();
}
inline void msg_head::set_allocated_server_type(std::string* server_type) {
  if (server_type != nullptr) {
    
  } else {
    
  }
  _impl_.server_type_.SetAllocated(server_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.server_type_.IsDefault()) {
    _impl_.server_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.msg_head.server_type)
}

// -------------------------------------------------------------------

// msg_a

// string server_type = 1;
inline void msg_a::clear_server_type() {
  _impl_.server_type_.ClearToEmpty();
}
inline const std::string& msg_a::server_type() const {
  // @@protoc_insertion_point(field_get:msg.msg_a.server_type)
  return _internal_server_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_a::set_server_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.server_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.msg_a.server_type)
}
inline std::string* msg_a::mutable_server_type() {
  std::string* _s = _internal_mutable_server_type();
  // @@protoc_insertion_point(field_mutable:msg.msg_a.server_type)
  return _s;
}
inline const std::string& msg_a::_internal_server_type() const {
  return _impl_.server_type_.Get();
}
inline void msg_a::_internal_set_server_type(const std::string& value) {
  
  _impl_.server_type_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_a::_internal_mutable_server_type() {
  
  return _impl_.server_type_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_a::release_server_type() {
  // @@protoc_insertion_point(field_release:msg.msg_a.server_type)
  return _impl_.server_type_.Release();
}
inline void msg_a::set_allocated_server_type(std::string* server_type) {
  if (server_type != nullptr) {
    
  } else {
    
  }
  _impl_.server_type_.SetAllocated(server_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.server_type_.IsDefault()) {
    _impl_.server_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.msg_a.server_type)
}

// int32 id = 2;
inline void msg_a::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t msg_a::_internal_id() const {
  return _impl_.id_;
}
inline int32_t msg_a::id() const {
  // @@protoc_insertion_point(field_get:msg.msg_a.id)
  return _internal_id();
}
inline void msg_a::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void msg_a::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:msg.msg_a.id)
}

// string time = 3;
inline void msg_a::clear_time() {
  _impl_.time_.ClearToEmpty();
}
inline const std::string& msg_a::time() const {
  // @@protoc_insertion_point(field_get:msg.msg_a.time)
  return _internal_time();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_a::set_time(ArgT0&& arg0, ArgT... args) {
 
 _impl_.time_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.msg_a.time)
}
inline std::string* msg_a::mutable_time() {
  std::string* _s = _internal_mutable_time();
  // @@protoc_insertion_point(field_mutable:msg.msg_a.time)
  return _s;
}
inline const std::string& msg_a::_internal_time() const {
  return _impl_.time_.Get();
}
inline void msg_a::_internal_set_time(const std::string& value) {
  
  _impl_.time_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_a::_internal_mutable_time() {
  
  return _impl_.time_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_a::release_time() {
  // @@protoc_insertion_point(field_release:msg.msg_a.time)
  return _impl_.time_.Release();
}
inline void msg_a::set_allocated_time(std::string* time) {
  if (time != nullptr) {
    
  } else {
    
  }
  _impl_.time_.SetAllocated(time, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.time_.IsDefault()) {
    _impl_.time_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.msg_a.time)
}

// string data = 4;
inline void msg_a::clear_data() {
  _impl_.data_.ClearToEmpty();
}
inline const std::string& msg_a::data() const {
  // @@protoc_insertion_point(field_get:msg.msg_a.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_a::set_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.msg_a.data)
}
inline std::string* msg_a::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:msg.msg_a.data)
  return _s;
}
inline const std::string& msg_a::_internal_data() const {
  return _impl_.data_.Get();
}
inline void msg_a::_internal_set_data(const std::string& value) {
  
  _impl_.data_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_a::_internal_mutable_data() {
  
  return _impl_.data_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_a::release_data() {
  // @@protoc_insertion_point(field_release:msg.msg_a.data)
  return _impl_.data_.Release();
}
inline void msg_a::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  _impl_.data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.msg_a.data)
}

// -------------------------------------------------------------------

// msg_b

// string server_type = 1;
inline void msg_b::clear_server_type() {
  _impl_.server_type_.ClearToEmpty();
}
inline const std::string& msg_b::server_type() const {
  // @@protoc_insertion_point(field_get:msg.msg_b.server_type)
  return _internal_server_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_b::set_server_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.server_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.msg_b.server_type)
}
inline std::string* msg_b::mutable_server_type() {
  std::string* _s = _internal_mutable_server_type();
  // @@protoc_insertion_point(field_mutable:msg.msg_b.server_type)
  return _s;
}
inline const std::string& msg_b::_internal_server_type() const {
  return _impl_.server_type_.Get();
}
inline void msg_b::_internal_set_server_type(const std::string& value) {
  
  _impl_.server_type_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_b::_internal_mutable_server_type() {
  
  return _impl_.server_type_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_b::release_server_type() {
  // @@protoc_insertion_point(field_release:msg.msg_b.server_type)
  return _impl_.server_type_.Release();
}
inline void msg_b::set_allocated_server_type(std::string* server_type) {
  if (server_type != nullptr) {
    
  } else {
    
  }
  _impl_.server_type_.SetAllocated(server_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.server_type_.IsDefault()) {
    _impl_.server_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.msg_b.server_type)
}

// int32 id = 2;
inline void msg_b::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t msg_b::_internal_id() const {
  return _impl_.id_;
}
inline int32_t msg_b::id() const {
  // @@protoc_insertion_point(field_get:msg.msg_b.id)
  return _internal_id();
}
inline void msg_b::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void msg_b::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:msg.msg_b.id)
}

// string time = 3;
inline void msg_b::clear_time() {
  _impl_.time_.ClearToEmpty();
}
inline const std::string& msg_b::time() const {
  // @@protoc_insertion_point(field_get:msg.msg_b.time)
  return _internal_time();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_b::set_time(ArgT0&& arg0, ArgT... args) {
 
 _impl_.time_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.msg_b.time)
}
inline std::string* msg_b::mutable_time() {
  std::string* _s = _internal_mutable_time();
  // @@protoc_insertion_point(field_mutable:msg.msg_b.time)
  return _s;
}
inline const std::string& msg_b::_internal_time() const {
  return _impl_.time_.Get();
}
inline void msg_b::_internal_set_time(const std::string& value) {
  
  _impl_.time_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_b::_internal_mutable_time() {
  
  return _impl_.time_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_b::release_time() {
  // @@protoc_insertion_point(field_release:msg.msg_b.time)
  return _impl_.time_.Release();
}
inline void msg_b::set_allocated_time(std::string* time) {
  if (time != nullptr) {
    
  } else {
    
  }
  _impl_.time_.SetAllocated(time, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.time_.IsDefault()) {
    _impl_.time_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.msg_b.time)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace msg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_msg_2eproto
